//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScaredFingers.UnitsConversion.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Units {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Units() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScaredFingers.UnitsConversion.Resources.Units", typeof(Units).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree Celcius.
        /// </summary>
        internal static string Celcius {
            get {
                return ResourceManager.GetString("Celcius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centimeter.
        /// </summary>
        internal static string Centimeter {
            get {
                return ResourceManager.GetString("Centimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centimeters.
        /// </summary>
        internal static string Centimeters {
            get {
                return ResourceManager.GetString("Centimeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centipoise.
        /// </summary>
        internal static string Centipoise {
            get {
                return ResourceManager.GetString("Centipoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centipoises.
        /// </summary>
        internal static string Centipoises {
            get {
                return ResourceManager.GetString("Centipoises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree Fahrenheit.
        /// </summary>
        internal static string Fahrenheit {
            get {
                return ResourceManager.GetString("Fahrenheit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feet.
        /// </summary>
        internal static string Feet {
            get {
                return ResourceManager.GetString("Feet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foot.
        /// </summary>
        internal static string Foot {
            get {
                return ResourceManager.GetString("Foot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gram.
        /// </summary>
        internal static string Gram {
            get {
                return ResourceManager.GetString("Gram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gram Per Cubic Centimeter.
        /// </summary>
        internal static string GramPerCubicCentimeter {
            get {
                return ResourceManager.GetString("GramPerCubicCentimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grams.
        /// </summary>
        internal static string Grams {
            get {
                return ResourceManager.GetString("Grams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grams Per Cubic Centimeter.
        /// </summary>
        internal static string GramsPerCubicCentimeter {
            get {
                return ResourceManager.GetString("GramsPerCubicCentimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inch.
        /// </summary>
        internal static string Inch {
            get {
                return ResourceManager.GetString("Inch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inches.
        /// </summary>
        internal static string Inches {
            get {
                return ResourceManager.GetString("Inches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree Kelvin.
        /// </summary>
        internal static string Kelvin {
            get {
                return ResourceManager.GetString("Kelvin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilogram.
        /// </summary>
        internal static string Kilogram {
            get {
                return ResourceManager.GetString("Kilogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilogram Per Cubic Meter.
        /// </summary>
        internal static string KilogramPerCubicMeter {
            get {
                return ResourceManager.GetString("KilogramPerCubicMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilogram Per Meter Second.
        /// </summary>
        internal static string KilogramPerMeter_Second {
            get {
                return ResourceManager.GetString("KilogramPerMeter_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilograms.
        /// </summary>
        internal static string Kilograms {
            get {
                return ResourceManager.GetString("Kilograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilograms Per Cubic Meter.
        /// </summary>
        internal static string KilogramsPerCubicMeter {
            get {
                return ResourceManager.GetString("KilogramsPerCubicMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilograms Per Meter Second.
        /// </summary>
        internal static string KilogramsPerMeter_Second {
            get {
                return ResourceManager.GetString("KilogramsPerMeter_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilometer.
        /// </summary>
        internal static string Kilometer {
            get {
                return ResourceManager.GetString("Kilometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilometers.
        /// </summary>
        internal static string Kilometers {
            get {
                return ResourceManager.GetString("Kilometers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liter.
        /// </summary>
        internal static string Liter {
            get {
                return ResourceManager.GetString("Liter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liters.
        /// </summary>
        internal static string Liters {
            get {
                return ResourceManager.GetString("Liters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter.
        /// </summary>
        internal static string Meter {
            get {
                return ResourceManager.GetString("Meter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meters.
        /// </summary>
        internal static string Meters {
            get {
                return ResourceManager.GetString("Meters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mile.
        /// </summary>
        internal static string Mile {
            get {
                return ResourceManager.GetString("Mile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miles.
        /// </summary>
        internal static string Miles {
            get {
                return ResourceManager.GetString("Miles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miligram.
        /// </summary>
        internal static string Miligram {
            get {
                return ResourceManager.GetString("Miligram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miligrams.
        /// </summary>
        internal static string Miligrams {
            get {
                return ResourceManager.GetString("Miligrams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milimeter.
        /// </summary>
        internal static string Milimeter {
            get {
                return ResourceManager.GetString("Milimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milimeters.
        /// </summary>
        internal static string Milimeters {
            get {
                return ResourceManager.GetString("Milimeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ounce.
        /// </summary>
        internal static string Ounce {
            get {
                return ResourceManager.GetString("Ounce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ounces.
        /// </summary>
        internal static string Ounces {
            get {
                return ResourceManager.GetString("Ounces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pascal Second.
        /// </summary>
        internal static string Pascal_Second {
            get {
                return ResourceManager.GetString("Pascal_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pascals Second.
        /// </summary>
        internal static string Pascals_Second {
            get {
                return ResourceManager.GetString("Pascals_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degrees Celcius.
        /// </summary>
        internal static string PCelsius {
            get {
                return ResourceManager.GetString("PCelsius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degrees Fahrenheit.
        /// </summary>
        internal static string PFahrenheit {
            get {
                return ResourceManager.GetString("PFahrenheit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degrees Kelvin.
        /// </summary>
        internal static string PKlevin {
            get {
                return ResourceManager.GetString("PKlevin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pound.
        /// </summary>
        internal static string Pound {
            get {
                return ResourceManager.GetString("Pound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pound Per Cubic Feet.
        /// </summary>
        internal static string PoundPerCubicFeet {
            get {
                return ResourceManager.GetString("PoundPerCubicFeet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pound Per Feet Second.
        /// </summary>
        internal static string PoundPerFeet_Second {
            get {
                return ResourceManager.GetString("PoundPerFeet_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pounds.
        /// </summary>
        internal static string Pounds {
            get {
                return ResourceManager.GetString("Pounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pounds Per Cubic Feet.
        /// </summary>
        internal static string PoundsPerCubicFeet {
            get {
                return ResourceManager.GetString("PoundsPerCubicFeet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pounds Per Feet Second.
        /// </summary>
        internal static string PoundsPerFeet_Second {
            get {
                return ResourceManager.GetString("PoundsPerFeet_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Gallons.
        /// </summary>
        internal static string PUSGallon {
            get {
                return ResourceManager.GetString("PUSGallon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Gallon.
        /// </summary>
        internal static string USGallon {
            get {
                return ResourceManager.GetString("USGallon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yard.
        /// </summary>
        internal static string Yard {
            get {
                return ResourceManager.GetString("Yard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yards.
        /// </summary>
        internal static string Yards {
            get {
                return ResourceManager.GetString("Yards", resourceCulture);
            }
        }
    }
}
